apiVersion: v1
kind: Service
metadata:
  name: galaxy-svc-k8s
  labels:
    app: galaxy-k8s
spec:
  type: NodePort
  ports:
   - name: http 
     port: 8080
     nodePort: 30700
  selector:
    app: galaxy-k8s
