kind: PersistentVolume
apiVersion: v1
metadata:
  name: k8s-galaxy-data-volume
  labels:
    type: nfs-on-master
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  #hostPath:
  #  path: "/tmp/data"
  nfs:
    server: k8s-master  # how the hell should I know the weave IP in a generic setting?
    path: "/home/centos/galaxy-data"

