#- name: SELinux - set permissive mode
#  command: setenforce 0
#  ignore_errors: yes

- selinux:
    policy: targeted
    state: permissive

#- name: Install k8s APT repo GPG key
#  apt_key:
#    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
#    state: present

- name: Adding k8s repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no
    #state: present
  register: kuberepo

- name: Install docker and kubernetes packages
  yum:
    name: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - docker
    - kubelet-1.7.3-1
    - kubeadm-1.7.3-1
    - kubectl
    - kubernetes-cni
    - nfs-utils

- name: Start docker service
  systemd: 
    state: started 
    name: docker 
    enabled: yes

- name: Update kubernetes packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Start kubelet service
  systemd: 
    state: started 
    name: kubelet
    enabled: yes

- name: Start nfs service
  systemd:
    state: started
    name: nfs-server.service
    enabled: yes

- name: Add hosts
  lineinfile:
    dest: "/etc/hosts"
    regexp: ".*{{ hostvars[item].ansible_hostname }}$"
    line: "{{ hostvars[item].ansible_ssh_host }} {{ hostvars[item].ansible_hostname }}"
    state: present
  when: hostvars[item].ansible_hostname is defined
  with_items: "{{groups['all'] | default([])}}"

- name: Add local host
  command: 'echo -e "server=8.8.8.8\nserver=8.8.4.4" > /etc/dnsmasq.conf && echo -e "$(hostname -i)\tlocalhost.$(hostname -d)" >> /etc/hosts && echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables'
  notify: 
    - restart dnsmasq

- name: Create OpenStack cloud configuration
  template:
    src: files/cloud-config.j2
    dest: /etc/kubernetes/cloud-config
    mode: 0600

- name: Override default kubeadm configuration to use the OpenStack cloud configuration
  copy:
    src: files/10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    mode: 0600
  notify:
    - restart kubelet
