- name: Create master security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-master"
    state: present
  when: state == "present"

- name: Create nodes security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-nodes"
    state: present
  when: state == "present"

- name: Allow traffic to master from anywhere
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-master"
    remote_ip_prefix: 0.0.0.0/0
  when: state == "present"

- name: Allow traffic to master from nodes
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-master"
    remote_group: "sg-{{ name }}-nodes"
  when: state == "present"


- name: Allow traffic to nodes from anywhere
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-nodes"
    remote_ip_prefix: 0.0.0.0/0
  when: state == "present"

- name: Allow traffic to nodes from nodes
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-nodes"
    remote_group: "sg-{{ name }}-nodes"
  when: state == "present"

- name: Allow traffic to nodes from master
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-nodes"
    remote_group: "sg-{{ name }}-master"
  when: state == "present"


- name: Delete master security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-master"
    state: absent
  when: state == "absent"

- name: Delete nodes security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-nodes"
    state: absent
  when: state == "absent"
